import { BLOCKCHAIN_NAMES } from '@app/common/types/exch-enum.type';

export enum TransakNetworks {
  ETHEREUM = 'ethereum',
  MAINNET = 'mainnet',
  OPTIMISM = 'optimism',
  ARBITRUM = 'arbitrum',
  POLYGON = 'polygon',
  SOLANA = 'solana',
  ALGORAND = 'algorand',
  BSC = 'bsc',
  AVAXCCHAIN = 'avaxcchain',
  TRON = 'tron',
  HEDERA = 'hedera',
  STELLAR = 'stellar',
  FUSE = 'fuse',
  CRONOS = 'cronos',
  FLOW = 'flow',
  APTOS = 'aptos',
  OSMOSIS = 'osmosis',
  OKXCHAIN = 'okxchain',
  BNB = 'bnb', /// ???? only one token? else are on BSC
  ZIL = 'zil',
  FANTOM = 'fantom',
  DOCK = 'dock',
  IMMUTABLE = 'immutable',
  MULTIVERSX = 'multiversx',
  IOTX = 'iotx',
  VELASEVM = 'velasevm',
  OASISNETWORK = 'oasisnetwork',
  NERVOS = 'nervos',
  WAX = 'wax',
  ASTAR = 'astar',
  AURORA = 'aurora',
  THUNDERCORE = 'thundercore',
  CELO = 'celo',
  WANCHAIN = 'wanchain',
  SHIDEN = 'Shiden',
  MOONRIVER = 'moonriver',
}

export const NAMES_TO_TRANSAK: { [key: string]: TransakNetworks } = {
  [BLOCKCHAIN_NAMES.ethereum]: TransakNetworks.ETHEREUM,
  [BLOCKCHAIN_NAMES.polygon]: TransakNetworks.POLYGON,
  [BLOCKCHAIN_NAMES.bitcoin]: TransakNetworks.MAINNET,
  [BLOCKCHAIN_NAMES.bnb]: TransakNetworks.BSC,
  [BLOCKCHAIN_NAMES.arbitrum]: TransakNetworks.ARBITRUM,
  [BLOCKCHAIN_NAMES.optimism]: TransakNetworks.OPTIMISM,
  [BLOCKCHAIN_NAMES.avalance]: TransakNetworks.AVAXCCHAIN,
};
